name = "LandRegistryPricePaidDB"
uuid = "2be6b72a-1d5f-47f2-9f22-1e32913d19b4"
authors = ["Matt Lawless"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
